# Generated by Django 2.2.1 on 2019-06-01 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WzUserStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('date_last_modif', models.DateTimeField(auto_now=True, verbose_name='Last changed')),
                ('uuid_reference', models.CharField(choices=[(0, 'wz-example')], default=['wz-example'], max_length=200)),
                ('uuid', models.CharField(default=None, max_length=200)),
                ('step', models.CharField(blank=True, choices=[('d000 STEP_1', 'd000 - Step 1'), ('d010 STEP_2', 'd010 - Step 2'), ('d020 STEP_3', 'd020 - Step 3')], default=None, max_length=200, null=True)),
                ('data', models.TextField(blank=True, default=None, null=True)),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
