# Generated by Django 3.0.2 on 2020-01-22 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wizard', '0005_auto_20190929_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wzuserstep',
            name='step',
            field=models.CharField(blank=True, choices=[('nlg-000 STEP_1', 'nlg-000 - Name / how many?'), ('nlg-010 STEP_2', 'nlg-010 - Step 2'), ('nlg-020 STEP_3', 'nlg-020 - Step 3'), ('nlg-020 STEP_4', 'nlg-020 - Step 4'), ('nxt-000 STEP_1', 'nxt-000 - Step 1'), ('nxt-010 STEP_2', 'nxt-010 - Step 2'), ('nxt-020 STEP_3', 'nxt-020 - Step 3'), ('spl-000 STEP_1', 'spl-000 - Step 1'), ('spl-010 STEP_2', 'spl-010 - Step 2'), ('spl-020 STEP_3', 'spl-020 - Step 3')], default=None, max_length=200, null=True),
        ),
    ]
