# Generated by Django 4.2.1 on 2023-05-15 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wizard", "0006_auto_20200122_2255"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wzuserstep",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
