# Generated by Django 2.2 on 2019-04-07 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interrogation',
            old_name='personnes',
            new_name='persons',
        ),
    ]
