# Generated by Django 2.2 on 2019-04-07 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190407_1957'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InterrogationPersonne',
            new_name='InterrogationPeople',
        ),
    ]
