# Generated by Django 2.2 on 2019-04-07 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190407_2325'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PeopleLink',
            new_name='PersonLink',
        ),
    ]
