# Generated by Django 2.2 on 2019-04-13 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20190408_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='reset_code',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
