# Generated by Django 2.2.1 on 2019-05-15 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_person_reset_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personlink',
            name='type_relation',
            field=models.IntegerField(choices=[(1, 'Parent <> Child'), (2, 'Husband <> Wife'), (3, 'Teacher <> Student')], default=3),
        ),
    ]
