# Generated by Django 2.2.1 on 2019-05-15 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20190515_1848'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interrogationperson',
            old_name='personne',
            new_name='person',
        ),
    ]
