# Generated by Django 2.2.1 on 2019-05-17 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20190515_1849'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personnesession',
            options={'ordering': ['pk'], 'verbose_name': 'Interrogation: session of a person', 'verbose_name_plural': 'Interrogation: sessions of a person'},
        ),
        migrations.RenameField(
            model_name='mot',
            old_name='important_pour_dictee',
            new_name='important',
        ),
    ]
