# Generated by Django 2.2.1 on 2019-05-17 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20190517_0827'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MotVoix',
            new_name='MotVoice',
        ),
    ]
