# Generated by Django 2.2.1 on 2019-05-17 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20190517_0831'),
    ]

    operations = [
        migrations.AddField(
            model_name='mot',
            name='generate_voice',
            field=models.BooleanField(default=True),
        ),
    ]
