# Generated by Django 2.2.1 on 2019-05-17 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_mot_generate_voice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mot',
            old_name='voix',
            new_name='voices',
        ),
    ]
