# Generated by Django 2.2.1 on 2019-05-17 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20190517_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='mot',
            name='generate_voice_language',
            field=models.CharField(blank=True, default=None, max_length=8, null=True),
        ),
    ]
