# Generated by Django 2.2.1 on 2019-05-17 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_mot_generate_voice_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mot',
            name='generate_voice',
            field=models.BooleanField(default=True, verbose_name='Generate if no file'),
        ),
        migrations.AlterField(
            model_name='mot',
            name='generate_voice_language',
            field=models.CharField(blank=True, default=None, max_length=8, null=True, verbose_name='Language'),
        ),
    ]
