# Generated by Django 2.2.1 on 2019-06-07 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_langue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='langue',
            name='locale',
            field=models.CharField(max_length=5),
        ),
    ]
