# Generated by Django 2.2.3 on 2019-08-01 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20190607_1706'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mot',
            new_name='Expression',
        ),
    ]
