# Generated by Django 2.2.3 on 2019-08-01 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20190801_1935'),
    ]

    operations = [
        migrations.RenameField(
            model_name='motvoice',
            old_name='mot',
            new_name='expression',
        ),
    ]
