# Generated by Django 2.2.3 on 2019-08-01 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20190801_2011'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MotVoice',
            new_name='ExpressionVoice',
        ),
    ]
