# Generated by Django 2.2.3 on 2019-08-01 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20190801_2013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='motgroupecategories',
            old_name='mot',
            new_name='expression',
        ),
    ]
