# Generated by Django 2.2.3 on 2019-08-02 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_auto_20190802_0933'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GroupeMots',
            new_name='GroupExpressions',
        ),
        migrations.RenameModel(
            old_name='ModeleInterrogationGroupeMots',
            new_name='ModeleInterrogationGroupExpressions',
        ),
    ]
