# Generated by Django 2.2.3 on 2019-08-02 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_auto_20190802_1206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupecategoriescategorie',
            old_name='groupe_categories',
            new_name='group_categories',
        ),
        migrations.RenameField(
            model_name='modeleinterrogationgroupexpressions',
            old_name='groupe_mots',
            new_name='groupe_expressions',
        ),
        migrations.RenameField(
            model_name='motgroupecategories',
            old_name='groupe_categories',
            new_name='group_categories',
        ),
        migrations.RenameField(
            model_name='phrasegroupecategories',
            old_name='groupe_categories',
            new_name='group_categories',
        ),
        migrations.AlterField(
            model_name='groupecategories',
            name='liens',
            field=models.ManyToManyField(blank=True, related_name='group_categories', through='app.GroupeCategoriesCategorie', to='app.Categorie'),
        ),
    ]
