# Generated by Django 2.2.3 on 2019-08-02 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_auto_20190802_1215'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GroupeCategories',
            new_name='CategoriesGroup',
        ),
        migrations.AlterModelOptions(
            name='motgroupecategories',
            options={'verbose_name': 'Expression: group of categories', 'verbose_name_plural': 'Expression: groups of categories'},
        ),
    ]
