# Generated by Django 2.2.3 on 2019-08-02 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_auto_20190802_1220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expression',
            old_name='groupes_categories',
            new_name='categories_groups',
        ),
        migrations.RenameField(
            model_name='groupecategoriesregles',
            old_name='groupecategories_1',
            new_name='categoriesgroup_1',
        ),
        migrations.RenameField(
            model_name='groupecategoriesregles',
            old_name='groupecategories_2',
            new_name='categoriesgroup_2',
        ),
        migrations.RenameField(
            model_name='phrase',
            old_name='groupes_categories',
            new_name='categories_groups',
        ),
    ]
