# Generated by Django 2.2.3 on 2019-08-02 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_auto_20190802_1233'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CategorieLien',
            new_name='CategoryLink',
        ),
        migrations.AlterField(
            model_name='categoriesgroupcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='app.Categorie', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='categoriesgroupcategory',
            name='group_categories',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group', to='app.CategoriesGroup', verbose_name='Group'),
        ),
    ]
