# Generated by Django 2.2.3 on 2019-08-02 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_auto_20190802_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorylink',
            name='dst',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_dst', to='app.Categorie', verbose_name='Dst link'),
        ),
        migrations.AlterField(
            model_name='categorylink',
            name='src',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_src', to='app.Categorie', verbose_name='Src link'),
        ),
    ]
