# Generated by Django 2.2.3 on 2019-08-02 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_auto_20190802_1238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorie',
            old_name='liens',
            new_name='links',
        ),
        migrations.RenameField(
            model_name='categoriesgroup',
            old_name='liens',
            new_name='links',
        ),
    ]
