# Generated by Django 2.2.4 on 2019-08-11 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_address_addresstype_entity_entityaddress_entitylink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entitylink',
            name='dst',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dst_tmp', to='app.Entity'),
        ),
        migrations.AlterField(
            model_name='entitylink',
            name='src',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='src_tmp', to='app.Entity'),
        ),
    ]
