# Generated by Django 2.2.4 on 2019-08-11 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_person_entity'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='entity_ptr',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,
                                       default=None, null=True, blank=True,
                                       serialize=False, to='app.Entity'),
            preserve_default=False,
        ),
    ]
