# Generated by Django 2.2.4 on 2019-08-11 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_person_entity_ptr_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='entity_ptr',
            field=models.OneToOneField(
                auto_created=True, default=1,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True, # primary_key=True,
                serialize=False, to='app.Entity'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='person',
            name='id',
        ),
    ]
