# Generated by Django 2.2.4 on 2019-08-11 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_person_entity_ptr_3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='relations',
        ),
        migrations.DeleteModel(
            name='PersonLink',
        ),
    ]
