# Generated by Django 2.2.5 on 2019-09-27 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_entityphone_phone_phonetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='entity_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.Entity'),
        ),
    ]
