# Generated by Django 2.2.5 on 2019-09-28 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_auto_20190927_1351'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='entityaddress',
            options={'verbose_name': 'Entity address', 'verbose_name_plural': 'Entity addresses'},
        ),
        migrations.AlterModelOptions(
            name='entitylink',
            options={'verbose_name': 'Entity link', 'verbose_name_plural': 'Entity links'},
        ),
        migrations.AlterModelOptions(
            name='entityphone',
            options={'verbose_name': 'Entity phone', 'verbose_name_plural': 'Entity phones'},
        ),
        migrations.AlterField(
            model_name='entitylink',
            name='link_type',
            field=models.IntegerField(choices=[(1, 'Parent <> Child'), (2, 'Husband <> Wife'), (3, 'Teacher <> Learner')], default=3),
        ),
    ]
