# Generated by Django 2.2.5 on 2019-09-29 10:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_auto_20190928_1200'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntitiesGroupType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Last changed')),
                ('date_v_start', models.DateTimeField(default=django.utils.timezone.now, verbose_name='V. start')),
                ('date_v_end', models.DateTimeField(blank=True, default=None, null=True, verbose_name='V. end')),
                ('name', models.CharField(blank=True, default='(no type)', max_length=200, null=True)),
            ],
            options={
                'ordering': ['date_v_start', 'date_updated', 'date_creation'],
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['date_v_start', 'date_updated', 'date_creation']},
        ),
        migrations.AlterModelOptions(
            name='addresstype',
            options={'ordering': ['date_v_start', 'date_updated', 'date_creation']},
        ),
        migrations.AlterModelOptions(
            name='entity',
            options={'ordering': ['date_v_start', 'date_updated', 'date_creation']},
        ),
        migrations.AlterModelOptions(
            name='langue',
            options={'ordering': ['date_v_start', 'date_updated', 'date_creation'], 'verbose_name_plural': 'Languages'},
        ),
        migrations.AlterModelOptions(
            name='phone',
            options={'ordering': ['date_v_start', 'date_updated', 'date_creation']},
        ),
        migrations.AlterModelOptions(
            name='phonetype',
            options={'ordering': ['date_v_start', 'date_updated', 'date_creation']},
        ),
        migrations.CreateModel(
            name='EntitiesGroup',
            fields=[
                ('entity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.Entity')),
                ('name', models.CharField(blank=True, default='(no name)', max_length=200, null=True)),
                ('entities_group_type', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.EntitiesGroupType')),
            ],
            options={
                'verbose_name': 'Entities group',
                'verbose_name_plural': 'Entities groups',
                'ordering': ['user__first_name', 'date_v_start', 'date_updated', 'date_creation', 'pk'],
            },
            bases=('app.entity',),
        ),
    ]
