# Generated by Django 2.2.5 on 2019-09-29 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0048_auto_20190929_1251'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entitiesgroup',
            options={'ordering': ['entities_group_type__name', 'name', 'date_v_start', 'date_updated', 'date_creation', 'pk'], 'verbose_name': 'Entities group', 'verbose_name_plural': 'Entities groups'},
        ),
        migrations.AlterModelOptions(
            name='entitiesgrouptype',
            options={'verbose_name': 'Entities group type',
                     'verbose_name_plural': 'Entities group types'},
        ),
    ]
