# Generated by Django 2.2.4 on 2019-09-30 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0049_auto_20190929_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entitylink',
            name='link_type',
            field=models.IntegerField(choices=[(1, 'Parent <> Child'), (2, 'Husband <> Wife'), (3, 'Teacher <> Learner'), (4, 'Group of learners <> Learner')], default=3),
        ),
    ]
